server:
  servlet:
    context-path: /order-ms
  port: 8001
spring:
  application:
    name: order-ms
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false
    database-change-log-table: ORDER_DB_CHANGELOG
    database-change-log-lock-table: ORDER_SERVICE_DB_LOCK
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: order_ms
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher