CREATE SCHEMA IF NOT EXISTS USER_MS;
SET SCHEMA 'USER_MS';
CREATE TABLE IF NOT EXISTS USER_MS.USER_
(
    ID_             UUID PRIMARY KEY            NOT NULL,
    USERNAME_       VARCHAR(256)                NOT NULL,
    PASSWORD_       VARCHAR(256)                NOT NULL,
    NAME_           VARCHAR(256)                NOT NULL,
    SURNAME_        VARCHAR(256)                NOT NULL,
    ROLE_           varchar(32)                 NOT NULL,
    IS_NON_EXPIRED_ BOOLEAN,
    IS_NON_LOCKED_  BOOLEAN,
    IS_ENABLED_     BOOLEAN                     NOT NULL,
    PHONE_          VARCHAR(256)                NOT NULL,
    CREATION_DATE_  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS PHONE_ID_I
    ON USER_MS.USER_ (PHONE_);
CREATE INDEX IF NOT EXISTS USERNAME_ID_I
    ON USER_MS.USER_ (USERNAME_);

CREATE TABLE IF NOT EXISTS USER_MS.TOKEN_
(
    ID_          BIGINT       NOT NULL
        CONSTRAINT ID_
            PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TOKEN_       VARCHAR(36) NOT NULL,
    EXPIRY_DATE_ TIMESTAMP    NOT NULL,
    USER_ID_     VARCHAR(36) NOT NULL
);

CREATE INDEX IF NOT EXISTS USER_ID_TOKEN_I
    ON USER_MS.TOKEN_ (USER_ID_);